package com.budakattu.sante.navigation

object NavRoutes {
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val LOGIN = "login"
    const val SIGNUP = "signup"
    const val BUYER_GRAPH = "buyer_graph"
    const val LEADER_GRAPH = "leader_graph"
    const val AUTH_GRAPH = "auth_graph"
    const val LEADER_HOME = "leader_home"
    const val LEADER_ADD_PRODUCT = "leader_add_product"
    const val LEADER_ORDERS = "leader_orders"
    const val LEADER_INVENTORY = "leader_inventory"
    const val CATALOG = "catalog"
    const val HERITAGE = "heritage"
    const val ORDERS = "orders"
    const val CART = "cart"
    const val CHECKOUT = "checkout"
    const val ORDER_CONFIRMATION = "order_confirmation/{orderId}"
    const val ORDER_CONFIRMATION_PREFIX = "order_confirmation"
    const val ORDER_DETAIL = "order_detail/{orderId}"
    const val ORDER_DETAIL_PREFIX = "order_detail"
    const val PROFILE = "profile"
    const val PRODUCT_DETAIL = "product/{productId}"
    const val PRODUCT_DETAIL_PREFIX = "product"
}
